version: '3.8'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 